name: taskme
description: App that teaches children responsibility

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.2.0
  simple_animations: ^1.3.3
  font_awesome_flutter: ^8.8.1
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.4+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Avenir
      fonts:
       - asset: assets/fonts/AvenirLTStd-Book.otf
       - asset: assets/fonts/AvenirLTStd-Medium.otf
       - asset: assets/fonts/AvenirLTStd-Roman.otf
    - family: HappyMarker
      fonts:
        - asset: assets/fonts/Happy-Marker.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

